fidor/fidor_schema

lib/fidor_schema_version.rb, schema/v1.0/base_types/base_types.json, schema/v1.0/transaction_type_details/internal_transfer_details.json, schema/v1.0/transaction_type_details/sepa_credit_transfer_details.json
Minor changes to consistantly treat all ids as string types.
=> API-355 all ids are string types

schema/v1.0/creditor_identity.json, schema/v1.0/sepa_mandate.json
It will need some more polishing, because of the changes @schorsch did on cleaning up the $ref mess.
=> Enable one creditor to use multiple UCIs

schema/v1.0/transaction_type_details/bonus_details.json, schema/v1.0/transaction_type_details/internal_transfer_details.json
Added `bonus_details.json` - `transaction_type_details` for `bonus` transactions.
=> Bonus transaction type details

schema/v1.0/transaction_type_details/internal_transfer_details.json
Added more sender related properties to `internal_transfer_details`
=> Newly introduce properties for the `internal_transfer_details`

schema/v1.0/transaction_type_details/bonus_details.json
Added `affiliate_transaction_type_category` to the `transaction_type_details` of `bonus` transactions
=> `affiliate_transaction_type_category`

schema/v1.0/transaction_type_details/gmt_details.json
Added `transaction_type_details` for the `gmt` related transactions.
=> The details for the gmt related transactions

schema/v1.0/transaction_type_details/credit_card_details.json
Added `cc_sequence` to `credit_card_details.json`
=> cc_sequence for credit card transactions

schema/v1.0/base_types/base_types.json, schema/v1.0/transaction.json
Moved `transaction_type` enum out of the `base_types.json` and added new transaction types
=> New tx types

schema/v1.0/base_types/base_types.json, schema/v1.0/transfer_approval.json
First draft for `transfer_approval.json`
=> Added schema for `transfer_approvals`

schema/v1.0/base_types/base_types.json, schema/v1.0/overdraft.json
=> Add overdraft schema

schema/v1.0/base_types/base_types.json
`capital_gains_tax` 
`solidarity_tax`
=> Just a couple of new tx_types

schema/v1.0/base_types/base_types.json, schema/v1.0/transaction.json
Updated transaction_type - reverted to previous state
=> Updated transaction_type - reverted to previous state

schema/v1.0/base_types/base_types.json, schema/v1.0/transaction.json
Added readOnly to transaction_type in transaction, remove readOnly from transaction_type in base_type
=> Change readOnly for transaction_type

schema/v1.0/base_types/base_types.json, schema/v1.0/preauth.json, schema/v1.0/preauth_type_details/capital_bond_details.json, schema/v1.0/preauth_type_details/credit_card_details.json, schema/v1.0/preauth_type_details/currency_order_details.json, schema/v1.0/preauth_type_details/gmt_details.json, schema/v1.0/preauth_type_details/internal_transfer_details.json, schema/v1.0/preauth_type_details/ripple_details.json
First rough draft version of the json schema for `preauth`
=> preauth -> rough draft

schema/v1.0/customer.json
Guys @razielgn, @gsamokovarov, please review.
=> Change to enable the customer creation

schema/v1.0/card.json, schema/v1.0/card/pin.json
@razielgn, @gsamokovarov, @schorsch 
Please notice that I changed `pin_code` to just `pin` in `/card/pin.json` - if there is a functionality already in place for showing the `pin` the response should be adapted to this change.
I also added `pin` to the `POST /cards` request and made it a `required` property.
=> card -> first draft

schema/v1.0/transaction.json
`created_at+updated_at` filters for transactions
=> Added `created_at_from/to` and `updated_at_from/to` filters

schema/v1.0/base_types/base_types.json, schema/v1.0/customer.json, schema/v1.0/legal.json
@agalloch, @gsamokovarov
Please review
=> Some minor changes to the customer.json schema.

schema/v1.0/preauth.json
@schorsch @agalloch - a very small change on the `preauths` filters
=> added amount filters on preauths

.travis.yml, schema/v1.0/card.json
=> Added `filter[states]` for the `cards` resource.

schema/v1.0/preauth_type_details/internal_transfer_details.json, schema/v1.0/transaction_type_details/internal_transfer_details.json
Added `receiver` to `internal_transfer_details.json` both for `transactions` and `preauths`
=> `receiver` attribute added to `transaction_` and `preauth_details`

schema/v1.0/password_reset.json
@avlazarov @agalloch please guys, review
=> Password reset endpoint

schema/v1.0/card.json
=> Moved the `cvc_code` into the main `properties` part

schema/v1.0/bank_check.json, schema/v1.0/validate.json
The idea is either validate `iban` and `account nr./bank code` separately:
- iban_check.json
- bank_account_check.json
or validate both by using one endpoint
- bank_account_check_draft.json
=> First draft for `iban` and `account number/bank code` check.

lib/fidor_schema_version.rb, schema/v1.0/card.json
@schorsch we have to publish it again - sorry
=> Added card’s `pan` number to the schema and bumped up the version

lib/fidor_schema_version.rb, schema/v1.0/bank_check.json, schema/v1.0/preauth_type_details/internal_transfer_details.json, schema/v1.0/transaction_type_details/internal_transfer_details.json
Added `recipient_name` to `preauth_type_details/internal_transfer_details.json` and `transaction_type_details/internal_transfer_details.json`
=> Recipient name

schema/v1.0/card_limit.json, schema/v1.0/message.json
=> First draft for the `messages`

schema/v1.0/message.json, schema/v1.0/notification.json
message.json and notification.json where referencing directory above instead of same directory.
=> Fixed reference to base_types. Was referencing non existing directories.

schema/v1.0/message.json
=> Add 'opened_at', 'archived_at' and 'category'; remove 'body'

lib/fidor_schema_version.rb, schema/v1.0/base_types/base_types.json, schema/v1.0/internal_transfer.json, schema/v1.0/preauth_type_details/internal_transfer_details.json, schema/v1.0/transaction_type_details/internal_transfer_details.json
Minor version bump up `0.10.7`.
=> Should fix the tests once we’ve built the gem.

lib/fidor_schema_version.rb, schema/v1.0/push_notification_token.json, schema/v1.0/push_notification_token/preferences.json
=> Push notification tokens

schema/v1.0/blocked_amount.json, schema/v1.0/emergency_loan.json
@agalloch 
We had a couple of empty schemas in the repo that can safely be removed.
=> Remove empty schemas

lib/fidor_schema_version.rb, schema/v1.0/account_limit.json
bumped up the gem version `0.10.10`
@agalloch
=> added `account_limit.json`

lib/fidor_schema_version.rb, schema/v1.0/customer.json
New loyalty endpoints and the schema bump `0.10.11`
=> New loyalty endpoints

lib/fidor_schema_version.rb, schema/v1.0/video_ident.json
=> video ident + version bump

lib/fidor_schema_version.rb
=> minor version bump up
